builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarm:
      - 6
      - 7
archives:
  - replacements:
      386: i386
      amd64: x86_64
      arm64: ARM64
      arm: ARM
      darwin: Darwin
      freebsd: FreeBSD
      linux: Linux
      windows: Windows
changelog:
  sort: asc
