version: 2
workflows:
  version: 2
  all:
    jobs:
      - build
      - docker:
          requires:
            - build
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raviqqe/muffet
    steps:
      - checkout
      - run: |
          apt -y update --fix-missing
          apt -y upgrade
          apt -y install rake
      - run: rake deps
      - run: rake lint
      - run: rake build
      - run: rake unit_test
      - run: curl -s https://codecov.io/bash | bash
      - run: |
          rake serve
          sleep 1
          rake integration_test
      - run: ./muffet --version > version
      - persist_to_workspace:
          root: .
          paths:
            - version
  docker:
    docker:
      - image: docker:17
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: |
          version=$(cat version)

          if [ $CIRCLE_BRANCH = master -a $version != $(docker run raviqqe/muffet --version) ]
          then
            docker build -t $DOCKER_USER/muffet .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOCKER_USER/muffet
            docker tag $DOCKER_USER/muffet $DOCKER_USER/muffet:$version
            docker push $DOCKER_USER/muffet:$version
          fi
